version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: url_shortener_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    container_name: url_shortener_redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped 
  backend:
    build:
      context: ./backend      # Path to your backend Dockerfile
      dockerfile: Dockerfile
    container_name: url_shortener_backend
    expose:
      - "5000"        
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/url_shortener
         # ↑ Connection string to Postgres (host is service name 'postgres')
      REDIS_URL: redis://redis:6379
        # ↑ Redis connection string (host is service name 'redis')
      PORT: 5000
    depends_on:
      - postgres           # Ensure Postgres starts before backend
      - redis               # Ensure Redis starts before backend
    restart: always         

  frontend:
    build:    
      context: .
      dockerfile: frontend/Dockerfile
    container_name: url_shortener_frontend
    ports:
      - "5000:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:           # Volume for Postgres data persistence

## We used the restart police of 'always' for theservices to ensure 
##they automatically restart if they crash or if the Docker daemon restarts. 
